spring:
  application:
    name: bi-krcc-migration

  datasource:
    url: jdbc:mysql://localhost:3306/bi_krcc_migration?useUnicode=true&characterEncoding=utf8
    username: batch
    password: batchbye
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발 중: update, 운영 환경: validate 또는 none
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        format_sql: true

#---
#spring:
#  config:
#    activate:
#      on-profile: mysql
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/bi_krcc_migration?useUnicode=true&characterEncoding=utf8
#      username: batch
#      password: batchbye
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  batch:
#    jdbc:
#      initialize-schema: always
##      table-prefix: SYSTEM_
#    job:
#      name: ${job.name:NONE}
#      enabled: true
